Logging types and subtypes
readthedocs/sphinx-autoapi pull request #277
Opened 2021-04-01 11:53 UTC by renefritze

This implements the proposal in https://github.com/readthedocs/sphinx-autoapi/issues/275

I'm not very sure about the subtypes. 

> "Unknown type" should possibly be an error so leave that one out for now. "Invalid all entry" could be invalid_sources.

Didn't come across either of those.

2021-04-02 18:30 UTC, AWhetter requested changes
Thanks for making this change. I've made a few suggestions. Let me know what you think.

2021-04-02 18:30 UTC, AWhetter commented on autoapi/mappers/dotnet.py
> +                        error_output, type="autoapi", subtype="metadata_generation"
Let's treat this as a `not_readable`. Similarly for the warning below as well.

2021-04-06 07:35 UTC, renefritze commented on autoapi/mappers/python/mapper.py
> +                **kwargs,
Yeah. I didn't touch that myself.

2021-04-06 08:22 UTC, renefritze commented on docs/reference/config.rst
> +     * python_import_resolution
That would be good, I agree. I've tried to add some now, but they feel somewhat clunky to me.

2021-04-13 02:57 UTC, AWhetter approved these changes
Looks good to me. Thanks for the changes!

2021-04-13 02:58 UTC, merged

2021-04-13 06:45 UTC, renefritze commented
Thank you for merging this. Would be great to get a new release soonish so I can start to use this myself.

2021-04-13 15:09 UTC, AWhetter commented
v1.8.0 was released with this in it.

2021-04-13 15:10 UTC, renefritze commented
Awesome. Thank you so much!